// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1E3-mw7EiTu4Sd-xd3R0sLmG_BrwMDSc',
    appId: '1:142251905393:web:1416dfa2a07fe38afb26d0',
    messagingSenderId: '142251905393',
    projectId: 'my-app-11208',
    authDomain: 'my-app-11208.firebaseapp.com',
    storageBucket: 'my-app-11208.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_9w5Ui34baAzOZqlLBfLhk7uthb6rEvU',
    appId: '1:142251905393:android:84a6c7a4ec5bb482fb26d0',
    messagingSenderId: '142251905393',
    projectId: 'my-app-11208',
    storageBucket: 'my-app-11208.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAxK4zSDJwwC3cPelr3Qq3fJWIgC4pFwo',
    appId: '1:142251905393:ios:1fcb60bffbe8077efb26d0',
    messagingSenderId: '142251905393',
    projectId: 'my-app-11208',
    storageBucket: 'my-app-11208.firebasestorage.app',
    androidClientId: '142251905393-68vnugfvj2boqrb2vni25873iuj9otpa.apps.googleusercontent.com',
    iosClientId: '142251905393-a7lr7ohtvojl4fski91noebkhuui1suu.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAppThumbnail',
  );

}